POST https://e6ttla0udc.execute-api.us-east-1.amazonaws.com/test/notetaker/api/notes
content-type: application/json

{
    "title": "My note Python",
    "content": "Python Python Python"
}

###

GET https://e6ttla0udc.execute-api.us-east-1.amazonaws.com/test/notetaker/api/notes

###

PATCH https://e6ttla0udc.execute-api.us-east-1.amazonaws.com/test/notetaker/api/notes/60cc8f64269c170007f29150
content-type: application/json

{
    "title": "Python2 !!!"
}

###

DELETE https://e6ttla0udc.execute-api.us-east-1.amazonaws.com/test/notetaker/api/notes/60cc8f64269c170007f29150
